### ISSUE TITLE
statement_descriptor provided, bank still shows "Stripe"

### ISSUE THREAD

**Issue by wwwroth** [cartalyst/stripe-laravel#25]
Currently using v. **5.0.***. I've provided a statement_descriptor in my API call to create a charge for a customer, but the bank still reflects the default "Stripe".

```
 $charge = $this->stripe->charges()->create([
     'customer' => $this->account->Stripe_CustomerID,
     'source' => $card->StripeCardID,
     'currency' => 'USD',
     'amount' => $amount,
     'statement_descriptor' => "Example.com"
]);
```

The Stripe log shows the statement_descriptor also.

```
{
  "customer": "cus_B8****Js2Gi",
  "source": "card_1A*****i5YemL",
  "currency": "USD",
  "amount": "5499",
  "statement_descriptor": "Example.com"
}
```

**Comment by brunogaspar** [comment]
Hello @wwwroth 

If the Stripe logs shows the correct descriptor, then it seems an issue with Stripe itself and you should contact Stripe instead.

**Comment by brunogaspar** [comment]
@wwwroth Going to close the ticket, as i don't think this is an issue with our package, since everything is working as expected from our end and it in fact shows the correct information on the Stripe logs.

If you still feel like it's an issue on our end, just let me know and i try to analyse the issue with a Stripe engineer.
