### ISSUE TITLE
Class 'Cartalyst\Stripe\Laravel\StripeServiceProvider' not found

### ISSUE THREAD

**Issue by howakx** [cartalyst/stripe-laravel#33]
I'm getting following error on Laravel 5.5. I have tried to reinstall both laravel and cartalyst but no luck.

**Comment by brunogaspar** [comment]
If the class is not being found, there are a couple of reasons:
1. Package is not installed or you tried to install but i failed
2. Autoload failed to complete due to other error
3. You maybe installed the incorrect package?

Run the following `composer show -i "cartalyst/*"` on your terminal and paste what it returns please.

I've done a fresh install of Laravel 5.5 and installed Cartalyst Stripe Laravel successfully, so i'm assuming it's something incorrect on your end.

**Comment by howakx** [comment]
Thank you for quick response. Below is the output that i got after running mentioned comand:

cartalyst/collections    v1.1.0 Collection Abstaction library for PHP.
cartalyst/stripe         v2.1.0 A comprehensive Stripe API package.
cartalyst/stripe-laravel v7.0.0 Laravel 5.5 integration for the Cartalyst Stripe package.

**Comment by brunogaspar** [comment]
When and where exactly does that error show up? I'm failing to reproduce it.

**Comment by howakx** [comment]
When i try to add providers in config/app.php

**Comment by brunogaspar** [comment]
Starting from Laravel 5.5 that's not required since it's "added" automatically (if the package itself is setup to do that), but we left that step on the documentation as i still prefer to specify it on projects, but either way, i'm not being able to reproduce your issue.

This is what i've ran to do a fresh install of Laravel 5.5, Cartalyst Stripe Laravel and to run a very quick test

```sh
composer create-project laravel/laravel stripe-laravel && cd stripe-laravel && composer require cartalyst/stripe-laravel
```

Once everything is installed i tested with Tinker

```sh
➜  stripe-laravel php artisan tinker
Psy Shell v0.8.15 (PHP 7.1.8 — cli) by Justin Hileman
>>> Cartalyst\Stripe\Laravel\Facades\Stripe::make()
RuntimeException with message 'The Stripe API key is not defined!'
>>>
```

Which tells me that everything is working as expected. So i can only assume it's something on your environment and not being able to reproduce it limits on what i can try to reproduce it and help you figure it out.

**Comment by howakx** [comment]
Resolved.. Thanks 👍

**Comment by cbj4074** [comment]
@howakx Would you be so kind as to share with us the solution in your case?

**Comment by howakx** [comment]
Actually the package was not getting installed properly. So, I have tested on different environment and it was working there perfectly.
