### ISSUE TITLE
Payment Error : Sending credit card numbers directly to the Stripe API is generally unsafe

### ISSUE THREAD

**Issue by dipakagile** [cartalyst/stripe-laravel#38]
In Laravel 5.1, we implemented version 3.0 of this package. It was working fine but from some time whenever I will go for payment module it shows below error. please check attached screenshot. It was working fine but from last 2 to 3 weeks ti shows this error and payment becomes fail. Right now we are working on a production server with live API.

**PHP Version :** PHP Version 7.0.22-0ubuntu0.16.04.1

**Laravel Version** : 5.1

**Package Version** : "cartalyst/stripe-laravel": "3.0.*"

![capture](https://user-images.githubusercontent.com/25260833/42610484-66f5e4d6-85af-11e8-9226-6005d96acb50.PNG)

**Comment by brunogaspar** [comment]
Hello @dipakagile 

This is not a bug on the our Stripe library but rather a security measure from Stripe because as the error/warning states, sending credit card information to your server can be dangerous and might not br PCI Compliant, depends on what you do with the data and how you store it.

This can be however disabled, you'll need to login into your Stripe Dashboard, go to Integration and then click on Advanced Settings.

Once there, you'll see a **Process payments unsafely** checkbox. Click on that and accept the other checkboxes.

I do however recommend that you revise your implementation and use Stripe Tokens instead of sending the card details to the server.

Hope it helps.

**Comment by dipakagile** [comment]
Thank you. I Got a solution. It was working fine with an old account which was created before oct 2017. After that time which accounts we created that account face this error. I got the solution using your package .just add card using token instead of its detail and need to pass card id on charge function. Its working fine thank you
