### ISSUE TITLE
 Call to undefined method Cartalyst\Stripe\Stripe::recipients()

### ISSUE THREAD

**Issue by raoikram** [cartalyst/stripe-laravel#59]
### Your Environment

- OS and Version: 64 Bir Windows 10
- PHP Version: 7.2.19
- Stripe Laravel Version: 11.0.*

### Expected behaviour

*Please describe what you are expecting to see happening.*
i was trying to create recipients but i sae this error on api call.

### Actual behaviour
  $recipient = $stripe->recipients()->create([
            'name' => 'John Doe',
            'type' => 'individual',
        ]);
        dd($recipient);
It saying :

Cartalyst\Stripe\Exception\MissingParameterException: Recipients have been deprecated and are no longer available. They have been replaced by Custom accounts (see https://stripe.com/docs/connect/recipient-account-migrations), which you should use if you're creating a new platform. Please reach out at https://support.stripe.com/contact if you have any questions. in file C:\laragon\www\rtn2-backend\vendor\cartalyst\stripe\src\Exception\Handler.php on line 125

### Steps to reproduce

*If your issue requires any specific steps to reproduce, please outline them here.*
1. install your package from **https://cartalyst.com/manual/stripe/2.0#laravel**
2. then in  controller i created  function
use Cartalyst\Stripe\Stripe;

    public function StripeRecipients(Request $request)
    {
      $recipient = $stripe->recipients()->create([
            'name' => 'John Doe',
            'type' => 'individual',
        ]);
        dd($recipient);
    }
3. call the api.

**Comment by brunogaspar** [comment]
As the error returned by Stripe mentions, you need to use the Accounts API, since they have deprecated the recipients API.

Not really much i can do about that, sorry.

**Comment by raoikram** [comment]
so this package is useless then ? as  it has deprecated functions?

**Comment by raoikram** [comment]
Can You giude me @brunogaspar  What should i use to transfer
how to connect user account and get their Account ID

**Comment by brunogaspar** [comment]
> so this package is useless then ? as it has deprecated functions?

I wouldn't call it useless just because an endpoint doesn't work, which is not really my fault, but either way, it's your opinion, use it or don't use it, it's all good. 

Stripe gives no information in advance on what they will deprecate or even remove, nor is this on their change-log (at least i couldn't find it :( ), since i'm not affiliated with Stripe, only when stuff doesn't work properly is when i know about it.

I understand your frustration, you just want things to work, i know, but receiving such demoralising comments is quite overwhelming, don't you think? It's open source after all, i get nothing from it (most people don't), so you should be more thankful for what people puts out there for you to use for **free** :)

> Can You giude me @brunogaspar What should i use to transfer
how to connect user account and get their Account ID

You need to switch to use the Accounts API, basically doing something`Stripe::account()->create($parameters)` and read what parameters it requires [here](https://stripe.com/docs/api/accounts/create) which is the official source of truth parameters wise.
Don't have documentation for this as of yet, but if needed for examples, you can check the [main library tests](https://github.com/cartalyst/stripe/blob/2.4/tests/Api/AccountTest.php), it has a few examples.

On https://stripe.com/docs/connect/recipient-account-migrations they mention you can "upgrade" which the wrong terminology, but instead, it should be "downgrade" to Stripe version `2017-02-14` and it should have Recipients still working, but, i haven't tested it, so i'm not claiming it works, it's their wording.

Hope it helps, if not just reply with the code that's not working and i'll try to assist as much as i can.

--

Just a small advice and take this how you see fit, but next time and/or in other repositories/projects, please try to be nicer when writing comments like the above, try to understand why something doesn't work first, not everyone will spend time replying you back when writing such comments.

I'm not mad or angry at you, not at all, just giving a bit of advice, that's all, i'm here to help and make sure your application works the best it can :)

**Comment by raoikram** [comment]
i was just asking you not pointing finger at you
Sorry if u mind @brunogaspar  I never meant to say anything to hurt yoU

**Comment by brunogaspar** [comment]
It's all good, don't worry about it.

Give it a go with the Accounts API please and let me know if you need help with it :)
